//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Brian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoster
    {
        public int RosterId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> JudgeId { get; set; }
    
        public virtual Judge Judge { get; set; }
        public virtual Client Client { get; set; }
    }
}
