//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Brian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPaymentLog
    {
        public int PaymentLogId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Description { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
