//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Brian.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSBrianEntities : DbContext
    {
        public CMSBrianEntities()
            : base("name=CMSBrianEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AvailableDay> AvailableDays { get; set; }
        public virtual DbSet<ClassTable> ClassTables { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<UserAvailableDay> UserAvailableDays { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<ClientPaymentLog> ClientPaymentLogs { get; set; }
        public virtual DbSet<ClassRoster> ClassRosters { get; set; }
        public virtual DbSet<ClientClass> ClientClasses { get; set; }
        public virtual DbSet<Judge> Judges { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
    }
}
