//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Brian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserDetailId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string UserId { get; set; }
        public string DateofBirth { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string JudgeName { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string SignedFormUrl { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UserImage { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
